# Tutorial 2.1: NumPy Introduction
Systems & Technologies: Python  
Week 2

In [1]:
# SETUP CODE - DON'T MODIFY THIS
# JUST EXECUTE IT
import pandas as pd
pd.set_option('display.max_colwidth', -1)

Today we move beyond learning the basics of Python as a programming language and start to learn how we can utilize some incredible open-source packages which are written in Python to perform data science.

## NumPy in 30 Seconds
NumPy, short for *Numerical Python*, is a package written by the Python community which you can **import** into your programs to provide an efficient way to store and operate on data sets through the custom data type, the **NumPy Array** (*`ndarray`*).  

In many ways, *`NumPy`* arrays are like Python's built in `list` type which you learned about in Module 1. The key differences are that *`NumPy`* arrays provide (1) lightning fast operations when dealing with a data set of (2) homogenous data (i.e. all integers, all floats, etc). 

<div class="alert alert-block alert-info">
Recently, the Python language itself introduced an `array` data type to efficiently store sets of single data type elements.  But NumPy arrays still provide significant benefits in comparison to the native Python `array` because of the methods (operations) that the `NumPy` authors built into them.
</div>

Equivalent operations (ex. getting the sum of 1000 numbers) will be 10-100 times faster when using `ndarray` objects vs. `list` objects.

## Heterogeneous Lists & Performance Problems
In the previous tutorial, we introduced the *`list`* data type. In our examples of this data type all of the elements have been of the same type. 

But this is not a requirement in Python.  You can place any number of different data types in a single list. For example: 

## Installing NumPy
Thus far, we've only interacted with objects and types that are part of Python's **Standard Library**. These are the objects that are part of core Python language and don't require any additional installation.

*`NumPy`* is a third party package or libary that is not a part of the standard library, so it has to be installed into our environment.

To keep people from getting bogged down with installation issues, we've already installed NumPy (along with all the other packages that you will need in the course) into your Cloud9 workspace.

<div class="alert alert-block alert-info">
Please review the <code>container-setup.md</code> file in the <code>how-to-guides</code> folder for additional information or ask your instructor.
</div>

## Importing NumPy
Before you can use any of `NumPy's` functionality, you'll need to import it into your programs.

In [2]:
# This should always go at the top of your program
import numpy

By convention, you'll find that most people in the Python community will import *`NumPy`* using *`np`* as an alias:

In [3]:
import numpy as np

This is the way we'll import and use NumPy. 

<div class="alert alert-block alert-warning">
<p>Usually, good progamming practice would avoid a two character variable name because to most people it is completely unclear as to what it represents. `np` could mean null pointer, non-primary, nearest point, etc. The only reason we do this in the case is because the `np` convention is extremely well known in the NumPy userbase.</p> 

<p><strong>But don't do this with your own variable names! Make them meaningful.</strong>
</p>

</div>


Once you've imported the numpy package as `np` you can interact with it as you would any other object. You can use `help()`, `?` and tab completition to start to learn what is available on it or any of it's nested objects, functions, etc.

## The Basics of NumPy Arrays

### Arrays can be Created from Lists
The simpliest way to create an `ndarray` is to simply pass a normal `list` to the `np.arrray()` constructor function like so:

In [4]:
list_of_ints = [0, 1, 2, 3, 4, 5]
int_array = np.array(list_of_ints)
int_array

array([0, 1, 2, 3, 4, 5])

<div class="alert alert-block alert-info">
A "constructor function (or method)" is just a function that constructs/creates a new object and returns it.
</div>

Now, you may have noticed that when we create an `ndarray` object from `list_of_ints` above, it didn't print out `ndarray([0, 1, 2, 3, 4, 5])` as the object representation, but `array([0, 1, 2, 3, 4, 5])`.

Make sure not to let this cause you problems when checking for the type of an object with `isinstance()` or `type()`. The real class of the object is `ndarray`.

In [5]:
# Notice what the type of the object actually is
type(int_array)

numpy.ndarray

In [6]:
# If you try to isinstance() with the wrong class name
# you'll have problems
isinstance(int_array, array)

NameError: name 'array' is not defined

### Passing Different Datatypes to a NumPy Array
If you try to pass in a list with different data types, *`NumPy`*  will attempt to convert them to a single type (this is called 'upcasting'). For example, let's say we had a list of student grades for our course that looked like this:

```python
student_grades = [87.5, 91, 86, 100.5] 
# Wow, somebody is so smart they got a 100.5
```

The first and fourth elements in this list are `float` objects while the second and third element are `int` objects. Let's see what happens when we convert this list to a NumPy array:

In [ ]:
np.array([87.5, 91, 86, 100.5])

You can see that the `int` objects were converted to `float` objects.

<div class="alert alert-block alert-warning">
<h5>Only One Data Type Allowed</h5>
<p>Remember, that `ndarray` objects can only hold elements of a single data type. That is why NumPy converted the int objects to float objects in this example.
</p>
</div>

One must be careful to avoid having `str` objects in the lists you pass to the `ndarray` constructor. If you do, NumPy will upcast all the elements to strings, which is make performing mathematical calcuations a real mess.

In [ ]:
bad_list_data = [12, 523, 23424, 'YUCKY']
nonideal_array = np.array(bad_list_data)

# Notice when this is printed that all the elements
# of the array will be strings (have quotes around them).
# Almost certainly not what you want...
nonideal_array

### Forcing an Array's Data Type
You also have the option of forcing all `ndarray` elements to have a specific data type.  Here I'll take a `list` of `float` objects and coerce them into `int` objects by specifying the **`dtype`** parameter on the `np.array` function.

In [ ]:
list_of_floats = [11.2, 57.6, 95.1]
np.array(list_of_floats, dtype=int)

Sometimes you can't coerce a data type. For instance, if there is a string in the source list that can't be converted to a numeric type.

In [ ]:
# This will work because the strings
# can be interpreted as numbers.
np.array([1, '2.5', 14, '-19'], dtype=float)

In [ ]:
# But this will fail...
np.array([1, '2.5 tacos', 14, '-19 burgers'], dtype=float)

The <code>dtype</code> parameter can take many different values in addition to these standard Python types: <code>int, float, bool, complex</code>.

In [ ]:
# Execute this cell to see the other options available for `dtype` from the NumPy website.
# As a beginner, you won't need to specify anything more than the basic Python data types,
# but this is a helpful reference.
numpy_data_types = pd.read_html(
    io="https://docs.scipy.org/doc/numpy/user/basics.types.html", index_col='Data type')[0]
numpy_data_types

### Arrays can be Multi-Dimensional
Ok, this might make your head hurt a little bit. 

NumPy arrays can be multi-dimensional. While in theory we could have an array with N levels of dimensions, you will most commonly work with 2-dimensional data as beginners. So let's look at a two dimensional array, which can be thought of a grid with x and y coordinates.

In [ ]:
# Don't focus on how this is being created. Just focus on the output.
two_dimensional_array = np.array([range(i, i + 3) for i in [2, 4, 6]])
two_dimensional_array

And now, just so that you know what they look like when displayed, here is  an example of a 3-dimensional array that has 4 elements in each dimension... which you could think of as a three dimensional cube.

In [ ]:
three_dimensional_array = np.ones(shape=(4, 4, 4))
three_dimensional_array

## NumPy Array Data Attributes
Like all objects, *`NumPy`* *`ndarray`* objects have a set of data attributes. Let's take moment to discuss some that you may find helpful:

1. `ndim`
1. `shape`
1. `size`
1. `dtype`

To get started, let's create 3 arrays.

In [ ]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print("One Dimensional Array", x1, '\n', sep='\n')
print("Two Dimensional Array", x2, '\n', sep='\n')
print("Three Dimensional Array", x3, '\n', sep='\n')

### `ndim` Attribute
Returns the number of dimensions a given array has.

In [ ]:
print(x1.ndim, x2.ndim, x3.ndim)

### `shape` Attribute
Returns the number of elements a in each dimension of an array. For our `x2` array we'd get this output:

```python
x2.shape
(3, 4)
```

If you look above, you'll see that the full represenation of our `x2` array was this:

```
[[6 7 9 1]
 [3 4 1 2]
 [6 7 0 7]]
```

The `(3, 4)` returned by `x2.shape` is referring to the fact that our array had three rows and four columns in each row.

### `size` Attribute
Returns the total number of elements across all dimensions of an array.

For our one-dimensional array, `size` will be 6.  
Our 2 dimensional array had dimensions of 3 and 4 elements, so `size` will be 12.  
Our 3 dimensional array had dimensions of 3, 4, and 5. Therefore it will have a total size of 60 elements.

In [ ]:
print("x1 size:", x1.size)
print("x2 size:", x2.size)
print("x3 size:", x3.size)

### `dtype` Attribute
Previously, we passed a `dtype` argument to the `np.array` constructor function to coerce the data type of the array's elements.

It comes about again here, but this time as an attribute of all NumPy arrays. Unsurprisingly, it tells you the data type of the elements held inside the array.

In [ ]:
float_array = np.array([1, 2, 3.1])
float_array.dtype

### `itemsize` and `nbytes` Attributes
Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.